import = ["~/.config/alacritty/themes/ayu.toml"]

[cursor]
style = "Block"

[font]
normal = {family = "Cascadia Code PL", style = "Regular"}

bold   = {family = "Cascadia Code PL", style = "Bold"}

italic = {family = "Cascadia Code PL", style = "Italic"}

size = 9

[window]
opacity = 1.00

padding = { x = 10, y = 10}
