#!/bin/bash

# Get the OS
OS=$(< /etc/issue awk '{print $1}' | xargs)

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true


picom &

if [[ "$OS" == "Parrot" ]]; then
  feh --bg-fill $HOME/Imágenes/Wallpapers/0x0001.png &
else
  feh --bg-fill $HOME/.local/catppuccin.jpg &
fi

$HOME/.config/polybar/./launch.sh &

xsetroot -cursor_name left_ptr
